#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/../.."

IMAGE="$(./tools/ensure-image)"

# -it to allow input() in run.py to work.
exec docker run -it --pull=never --rm --network=none -v "$PWD:/work" -w /work "$IMAGE" python3 tools/test/run.py
